apiVersion: v1
kind: Pod
metadata:
  name: icit-private-reg-test
spec:
  containers:
  - name: icit-private-reg-container-test
    image: ntxvm015.iccluster.epfl.ch/cvlab-k8s-master/tfkeras:v1
    command:
      - sleep
      - infinity
  imagePullSecrets:
  - name: icitkey 
