apiVersion: v1
kind: Pod
metadata:
  name: private-reg-test
spec:
  containers:
  - name: private-reg-container-test
    image: docker.io/kcyu2014/k8s-masterpiece:ubuntu-test
    command:
      - sleep
      - infinity
  imagePullSecrets:
  - name: regsecret
