apiVersion: v1
kind: Pod
metadata:
  name: kyu-pvc-gpu-1
spec:
  containers:
  - name: cuda-container
    image: nvidia/cuda
    resources:
      limits:
        nvidia.com/gpu: 1 # requesting 2 GPUs
    command:
    - sleep
    - infinity
  # mount the data volumes
    volumeMounts:
      - mountPath: /home/kyu
        name: cvlabdata3
        subPath: kyu
      - mountPath: /cvlabdata3
        name: cvlabdata3
  volumes:
  - name: cvlabdata3
    persistentVolumeClaim:
      claimName: cvlab-scratch
---
