apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod-test-1
spec:
  containers:
    - name: cuda-container
      image: nvidia/cuda
      resources:
        limits:
          nvidia.com/gpu: 1 # requesting 2 GPUs
      command:
      - sleep
      - infinity
---
