kind: Service
apiVersion: v1
metadata:
  name: kyu-tf-svc-test
  labels:
    name: kyu-tf-svc
spec:
  type: LoadBalancer
  ports:
    - port: 8888
      protocol: TCP
  selector: # The listened pod name
    name: kyu-tf-pod
