---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.2.0 (99f88ef)
  creationTimestamp: null
  labels:
    io.kompose.service: redis
  name: redis-pod-test
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: redis
    spec:
      containers:
      - args:
        - redis-server
        - /usr/local/etc/redis/redis.conf # Add this to the mount redis.conf
        image: redis:3.2
        name: gospider-redis
        ports:
        - containerPort: 6379 # This is the port of container side
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: redis-claim-0
          subPath: kyu/amazonspider/
        - mountPath: /usr/local/etc/redis # where I store the redis.conf
          name: redis-claim-0
          subPath: kyu/redis
      restartPolicy: Always
      volumes:
      - name: redis-claim-0
        persistentVolumeClaim:
          claimName: e73d5238-126c-4db6-aa8d-157412c5889c-cvlab
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: redis-svc-test
  labels:
    io.kompose.service: redis
spec:
  ports:
  - name: "6379"
    port: 6397
    targetPort: 6379
  selector:
    io.kompose.service: redis
status:
  loadBalancer: {}
---
