apiVersion: v1
kind: Pod
metadata:
  name: kyu-pod-tf-jupyter-gpu
  labels:
    name: kyu-pod-tf-jupyter-gpu
spec:
  volumes:
  - name: site-data
    persistentVolumeClaim:
      claimName: pvc-nfs-kyu-lamp
  - hostPath:
      path: /usr/lib/nvidia-375/bin
    name: bin
  - hostPath:
      path: /usr/lib/nvidia-375
    name: lib
  containers:
  - name: tensorflow
    image: tensorflow/tensorflow:latest-gpu
    ports:
    - containerPort: 8888
    resources:
      limits:
        alpha.kubernetes.io/nvidia-gpu: 1
    volumeMounts:
    - mountPath: /usr/local/nvidia/bin
      name: bin
    - mountPath: /usr/local/nvidia/lib
      name: lib
    - mountPath: /notebooks/shared_volume
      name: site-data
      subPath: tf-jupyter-gpu

