apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-caperez-lamp
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    request:
      storage: 2Gi

        
