---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.2.0 (99f88ef)
  creationTimestamp: null
  labels:
    io.kompose.service: mysqldb
  name: mysqldb
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mysqldb
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          value: happyhack
        image: mysql:5.7
        name: gospider-mysqldb
        ports:
        - containerPort: 3307
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: site-data
          subPath: kyu/mysql
        - mountPath: /cvlabdata3
          name: site-data
        - mountPath: /home/kyu
          name: site-data
          subPath: kyu
      volumes:
      - name: site-data
        persistentVolumeClaim:
          claimName: e73d5238-126c-4db6-aa8d-157412c5889c-cvlab
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.2.0 (99f88ef)
  creationTimestamp: null
  labels:
    io.kompose.service: mysqldb
  name: kyu-mysqldb-test
spec:
  ports:
  - name: "3307"
    port: 3307
    targetPort: 3307
  selector:
    io.kompose.service: mysqldb
status:
  loadBalancer: {}