apiVersion: v1
kind: Pod
metadata:
  name: kyu-spider-pod-test
  label: kyu-spider-pod
spec:
  containers:
  - name: ubuntu-spider-test
    image: ubuntu:16.04
    ports:
    - containerPort: 12345
    volumeMounts:
    - mountPath: /log
      name: cvlabdata3
      subPath: kyu/amazonspider/log/1
    - mountPath: /data
      name: cvlabdata3
      subPath: kyu/amazonspider/data
    - mountPath: /gopath
      name: cvlabdata3
      subPath: kyu/go
    - mountPath: /go_root
      name: cvlabdata3
      subPath: kyu/.local/go
    - mountPath: /workspace
      name: cvlabdata3
      subPath: kyu/go/src/github.com/hunterhug/AmazonBigSpider
    env:
    - name: GOPATH
      value: /gopath
    - name: GOROOT
      value: /go_root
    command:
      - sleep
      - infinity
    # args:
    # - /workspace/spider/usa/UASIN
    # - /workspace/spider/usa/ULIST
  volumes:
  - name: cvlabdata3
    persistentVolumeClaim:
      claimName: e73d5238-126c-4db6-aa8d-157412c5889c-cvlab
---
apiVersion: v1
kind: Service
metadata:
  name: kyu-spider-svc-test
spec:
  type: LoadBalancer
  ports:
  - name: "usa"
    port: 12345
    targetPort: 12345
  selector:
    label: kyu-spider-pod
status:
  loadBalancer: {}
